/**
 * Error codes returned in { error: { code, message, field } }.
 */

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  NOT_FOUND: 'NOT_FOUND',
  DATA_ENGINE_UNAVAILABLE: 'DATA_ENGINE_UNAVAILABLE',
  LLM_UNAVAILABLE: 'LLM_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  PAYLOAD_TOO_LARGE: 413,
  INTERNAL_ERROR: 500,
  BAD_GATEWAY: 502,
};
