"""Spectral layer: compact, diagonal representation of the candidate features.

What it computes
----------------
Let X (n x d) be the encoded, centred feature matrix (see encode.py). Its thin
SVD X = U S V^T gives the eigen-decomposition of the sample covariance

    Sigma = X^T X / (n - 1) = V Lambda V^T,     Lambda = S^2 / (n - 1).

1. Truncation with a certified error (Eckart-Young-Mirsky). The best rank-k
   approximation X_k = U_k S_k V_k^T satisfies exactly
       ||X - X_k||_F^2 = sum_{i>k} s_i^2,     ||X - X_k||_2 = s_{k+1}.
   We keep the smallest k whose retained energy reaches `energy` (95 %), and
   report the discarded fraction as the truncation error. No guesswork.

2. Diagonal algebra instead of matrix algebra. Conjugation by V is an algebra
   isomorphism between the commutative algebra generated by Sigma and diagonal
   matrices, i.e. R^k with pointwise product (spectral theorem / functional
   calculus): f(Sigma) = V f(Lambda) V^T for any f. So Sigma^{-1}, Sigma^{-1/2},
   Mahalanobis distances, etc. become element-wise operations on the k
   eigenvalues: O(k) per candidate instead of an O(d^3) inversion, and no
   ill-conditioned inverse is ever formed.

3. Numerical stability. We take the SVD of X, never eigh(X^T X): forming the
   covariance squares the condition number (kappa(X^T X) = kappa(X)^2) and
   loses up to half of the significant digits. Orthogonal transforms have
   condition number 1, so rotating into the eigenbasis adds no error.

4. Monitoring statistics (standard multivariate SPC):
   * Hotelling T^2 = sum_i z_i^2 / lambda_i on the retained components
     (Mahalanobis distance, element-wise thanks to point 2);
   * Q / SPE = ||x - x_k||^2, the residual in the discarded subspace.
   A candidate is "atypical" if T^2 exceeds the Phase-I control limit. Because
   the mean and covariance are *estimated from the same n points* that are
   being screened, the exact null distribution (Gaussian features) is a Beta,
   not a chi-square:  T^2 * n / (n-1)^2 ~ Beta(k/2, (n-k-1)/2)
   (Tracy, Young & Mason 1992). The chi-square quantile is only its n -> inf
   limit and is used as fallback when scipy is missing. For non-Gaussian
   (ordinal, bounded) features the limit is a calibrated heuristic.

5. Explanations in original units. T^2 = x^T M x with M = V_k Lambda_k^{-1} V_k^T.
   The contributions c_j = x_j (M x)_j sum exactly to T^2, so we can say *which
   original feature* makes a candidate atypical. The rotated basis itself is
   never shown to the breeder.

Scope: this layer never decides a colour. It flags atypical candidates and
finds similar ones (compare_candidates); the rules decide.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from . import accel


def chi2_quantile(q: float, dof: int) -> float:
    """Chi-square quantile. Uses scipy when present, else Wilson-Hilferty (error < 1 % for dof >= 3)."""
    try:
        from scipy.stats import chi2
        return float(chi2.ppf(q, dof))
    except ImportError:
        # Normal quantile via Acklam-style rational approximation of the probit.
        z = _probit(q)
        return dof * (1.0 - 2.0 / (9.0 * dof) + z * math.sqrt(2.0 / (9.0 * dof))) ** 3


def _probit(p: float) -> float:
    # Beasley-Springer-Moro approximation, accurate to ~1e-9 in the central region.
    a = [2.50662823884, -18.61500062529, 41.39119773534, -25.44106049637]
    b = [-8.47351093090, 23.08336743743, -21.06224101826, 3.13082909833]
    c = [0.3374754822726147, 0.9761690190917186, 0.1607979714918209, 0.0276438810333863,
         0.0038405729373609, 0.0003951896511919, 0.0000321767881768, 0.0000002888167364,
         0.0000003960315187]
    y = p - 0.5
    if abs(y) < 0.42:
        r = y * y
        return y * (((a[3] * r + a[2]) * r + a[1]) * r + a[0]) / ((((b[3] * r + b[2]) * r + b[1]) * r + b[0]) * r + 1.0)
    r = math.log(-math.log(p if y < 0 else 1.0 - p))
    x = c[0] + r * (c[1] + r * (c[2] + r * (c[3] + r * (c[4] + r * (c[5] + r * (c[6] + r * (c[7] + r * c[8])))))))
    return -x if y < 0 else x


def t2_limit(n: int, k: int, q: float) -> float:
    """Phase-I upper control limit for Hotelling T^2 with estimated mean/covariance."""
    try:
        from scipy.stats import beta
        if n - k - 1 > 0:
            return float((n - 1) ** 2 / n * beta.ppf(q, k / 2.0, (n - k - 1) / 2.0))
    except ImportError:
        pass
    return chi2_quantile(q, k)


@dataclass
class SpectralModel:
    mean: np.ndarray
    components: np.ndarray        # V_k, shape (d, k)
    eigenvalues: np.ndarray       # lambda_1..lambda_k
    all_singular: np.ndarray      # s_1..s_r (for the error certificate)
    feature_names: list[str]
    k: int
    energy_retained: float
    truncation_error_rel: float   # ||X - X_k||_F^2 / ||X||_F^2
    spectral_error: float         # s_{k+1} (operator-norm error)
    t2_threshold: float

    @classmethod
    def fit(cls, x: np.ndarray, names: list[str], energy: float = 0.95, quantile: float = 0.975) -> "SpectralModel":
        n = x.shape[0]
        mean = x.mean(axis=0)
        xc = x - mean
        _, s, vt = np.linalg.svd(xc, full_matrices=False)
        tol = s.max() * max(xc.shape) * np.finfo(float).eps if s.size else 0.0
        s = s[s > tol]                      # numerical rank
        vt = vt[: len(s)]
        e = s ** 2
        total = e.sum()
        cum = np.cumsum(e) / total
        k = int(np.searchsorted(cum, energy) + 1)
        k = min(k, len(s))
        return cls(
            mean=mean,
            components=vt[:k].T,
            eigenvalues=e[:k] / (n - 1),
            all_singular=s,
            feature_names=list(names),
            k=k,
            energy_retained=float(cum[k - 1]),
            truncation_error_rel=float(e[k:].sum() / total),
            spectral_error=float(s[k]) if k < len(s) else 0.0,
            t2_threshold=t2_limit(n, k, quantile),
        )

    # --- coordinates -----------------------------------------------------------
    def scores(self, x: np.ndarray) -> np.ndarray:
        """Coordinates in the eigenbasis (n x k)."""
        return (x - self.mean) @ self.components

    def whiten(self, x: np.ndarray) -> np.ndarray:
        """Sigma^{-1/2} in the eigenbasis: an element-wise division, no inverse formed."""
        return self.scores(x) / np.sqrt(self.eigenvalues)

    # --- monitoring statistics ---------------------------------------------------
    def hotelling_t2(self, x: np.ndarray) -> np.ndarray:
        return np.sum(self.whiten(x) ** 2, axis=1)

    def residual_q(self, x: np.ndarray) -> np.ndarray:
        xc = x - self.mean
        return np.sum((xc - self.scores(x) @ self.components.T) ** 2, axis=1)

    def contributions(self, x_row: np.ndarray) -> np.ndarray:
        """Per-original-feature contributions to T^2 (they sum exactly to T^2)."""
        xc = x_row - self.mean
        m_x = self.components @ ((self.components.T @ xc) / self.eigenvalues)
        return xc * m_x

    def nearest(self, x: np.ndarray, query_idx: int, k: int = 5) -> list[tuple[int, float]]:
        """k nearest candidates in whitened space (Mahalanobis metric)."""
        w = self.whiten(x)
        idx, d2 = accel.knn(w[[query_idx]], w, k + 1)
        return [(int(i), float(np.sqrt(max(d, 0.0)))) for i, d in zip(idx[0], d2[0]) if int(i) != query_idx][:k]

    def certificate(self) -> dict:
        """Everything a reviewer needs to check the truncation claim."""
        total = float((self.all_singular ** 2).sum())
        return {
            "features": len(self.feature_names),
            "numerical_rank": int(len(self.all_singular)),
            "retained_components": self.k,
            "energy_retained": round(self.energy_retained, 4),
            "truncation_error_rel_frobenius_sq": round(self.truncation_error_rel, 4),
            "spectral_norm_error": round(self.spectral_error, 4),
            "eigenvalues": [round(float(v), 4) for v in self.eigenvalues],
            "explained_ratio": [round(float(s ** 2 / total), 4) for s in self.all_singular[: self.k]],
            "t2_threshold": round(self.t2_threshold, 3),
            "condition_number_data": round(float(self.all_singular[0] / self.all_singular[-1]), 2),
        }
